### ISSUE TITLE
Still alive?

### ISSUE THREAD

**Issue by RdeWilde** [codesipcoffee/restvertx#1]
Is there still something coming for this project, i.e. will it ever be made ready for production?

**Comment by codesipcoffee** [comment]
Good question

I haven't had much time to spend on this in the last few months, literally nobody has expressed interest and a project I was going to use it on was cancelled, and not to mention there are similar things in the Vert.x awesome page competing with this

Do you have a project this would be useful for?  Please let me know if you seriously would like to take this to be taken to the next level, I could be motivated to work on it more if there's enough interest

**Comment by RdeWilde** [comment]
Could you share a little of what you think that are similar things? I would not want to diverse energy becuase of maintaining two equal projects ofcourse.

You mean Nubes? Or JAX-RS/Jersey?

"I could be motivated to work on it more ...", you being far with yourself? ;-)

**Comment by codesipcoffee** [comment]
Ha ha I am not far, but just trying to keep it real.  Life doesn't grant me many opportunities for much free time

I would say Jersey first since it's been around longer and has been further developed, and then Nubes

Here is an example piece of code I pulled from the official Jersey site, it looks kind of similar:

```java
package com.example;
 
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
 
/**
 * Root resource (exposed at "myresource" path)
 */
@Path("myresource")
public class MyResource {
 
    /**
     * Method handling HTTP GET requests. The returned object will be sent
     * to the client as "text/plain" media type.
     *
     * @return String that will be returned as a text/plain response.
     */
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String getIt() {
        return "Got it!";
    }
}
```
And many more examples here: https://github.com/jersey/jersey/tree/2.22.1/examples

**Comment by RdeWilde** [comment]
I know that problem ;-)

OK, thanks. Let me look into the alternatives a bit more before 'asking' for any of your rare spare time :) Thanks again
