### ISSUE TITLE
Request body in path?

### ISSUE THREAD

**Issue by RdeWilde** [codesipcoffee/restvertx#2]
```
@Path("shoppingLists/:request")
public String getShoppingListPost(ShoppingListRequest request)
{ 
```

From the example, why is the :request in the path while it is a request body (so won't shop up in the path); it has a name and/or id. Am I missing something?

**Comment by codesipcoffee** [comment]
Hi RdeWilde,

<b>:request</b> is a json serialized object that I want to pass to my handling method as an argument that will be deserialized into my pretend ShoppingListRequest object

The <b>ShoppingListRequest</b> object may define certain parameters for the requested action, it may not always be as simple as "get the list with this name or id".  If I used name or id only, it's not very future proof.  If I specify a ShoppingListRequest, I can always add more complexity to the ShoppingListRequest object without modifying request parameters, and in my opinion is a cleaner way to specify a complex object in a request like this at the cost of deserializing json, albeit a small hit on time, the tradeoff is yours to decide

Please correct me if I'm wrong, but I think your question really is why use a complex object for something that may only require a name and/or id?  This is a valid question, and if you think that's all it will ever take, then I would change it to something like this:

``` java
@Path("shoppingLists/:id")
public String getShoppingListById(long id)
{ 
...
}
```
or
```java
@Path("shoppingLists/:name")
public String getShoppingListByName(String name)
{ 
...
}
```
I think I make a better example here: https://github.com/codesipcoffee/restvertx/blob/example/src/main/java/example/project/Singers.java

**Comment by RdeWilde** [comment]
Thanks, very clear!
